version: '3'
services:

  directus:
    container_name: directus
    image: directus/directus:11.1.0
    ports:
      - 8055:8055
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - ./uploads:/directus/uploads
      # Make sure to also mount the volume when using SQLite
      # - ./database:/directus/database
      # If you want to load extensions from the host
      - ./extensions:/directus/extensions/


    networks:
      - directus
    environment:
      TZ : 'Asia/Ho_Chi_Minh'
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: 'elujlp-Bj-akA9Fq8SQvJzesHB_R3p5j'

      DB_CLIENT: 'pg'
      # DB_HOST: '192.168.3.229'
      DB_HOST: '162.248.102.236'
      DB_PORT: '5500'
      DB_DATABASE: 'health-care'
      DB_USER: 'health-care'
      DB_PASSWORD: 'u~G24WsNV(XKe8d+'

      DB_SSL: 'false'

      # CACHE_ENABLED: 'true'
      #CACHE_STORE: 'redis'
      #CACHE_REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: 'admin@gmail.com'
      ADMIN_PASSWORD: '12345678'
      
      ACCESS_TOKEN_TTL : '30d'
      
      CORS_ENABLED: 'true'
      CORS_ORIGIN: 'true'
      CORS_METHODS: 'GET,POST,PATCH,DELETE'
      CORS_ALLOWED_HEADERS: 'Content-Type,Authorization'
      CORS_EXPOSED_HEADERS: 'Content-Range'
      CORS_CREDENTIALS: 'true'
      CORS_MAX_AGE: 18000
      
      RATE_LIMITER_ENABLED: false


      RATE_LIMITER_STORE: memory

      RATE_LIMITER_POINTS: 25

      RATE_LIMITER_DURATION: 1

      CACHE_ENABLED: false

      REFRESH_TOKEN_TTL: "7d"
      
      REFRESH_TOKEN_COOKIE_SECURE: false
      
      REFRESH_TOKEN_COOKIE_SAME_SITE: "lax"
      
      REFRESH_TOKEN_COOKIE_NAME: "directus_refresh_token"
      
      SESSION_COOKIE_TTL: "1d"
      
      SESSION_COOKIE_SECURE: false
      
      SESSION_COOKIE_SAME_SITE: "lax"
      
      SESSION_COOKIE_NAME: "directus_session_token"
      
      
      #AUTH_PROVIDERS : "google"
      
      PUBLIC_URL: "http://162.248.102.236:8055"
      
      EXTENSIONS_PATH : "./extensions/"
      #EXTENSIONS_AUTO_RELOAD : "true"
      
      
      #REFRESH_TOKEN_COOKIE_DOMAIN : "biplus.com.vn" # Replace XXXX with the domain of your Directus instance. For example "directus.myserver.com"
      #REFRESH_TOKEN_COOKIE_SECURE : "true"
      #REFRESH_TOKEN_COOKIE_SAME_SITE : "None"
      
      #REFRESH_TOKEN_COOKIE_SECURE : "false"
      #REFRESH_TOKEN_COOKIE_SAME_SITE : "lax"

      #AUTH_GOOGLE_DRIVER : "openid"
      #AUTH_GOOGLE_CLIENT_ID : "1088001911485-8o8o2oa3c9hdhd8fmiihsqsn9ktgo6gr.apps.googleusercontent.com" # Replace XXXX with the Client ID from Step 6
      #AUTH_GOOGLE_CLIENT_SECRET : "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" # Replace XXXX with the Client Secret from Step 6
      #AUTH_GOOGLE_ISSUER_URL : "https://accounts.google.com"
      #AUTH_GOOGLE_IDENTIFIER_KEY : "email"
      #AUTH_GOOGLE_ICON : "google"
      #AUTH_GOOGLE_LABEL : "Google"
      #AUTH_GOOGLE_ALLOW_PUBLIC_REGISTRATION : "true" # This allows users to be automatically created on logins. Use "false" if you want to create users manually
      #AUTH_GOOGLE_DEFAULT_ROLE_ID : "088de733-2493-49dc-a5e6-43545345f480" # Replace this with the Directus Role ID you would want for new users. If this is not properly configured, new users will not have access to Directus

      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      # PUBLIC_URL: 'https://directus.example.com'

      EMAIL_TEMPLATES_PATH: './templates'
      EMAIL_FROM: "trinhthuc130902@gmail.com"
      ## Email (SMTP Transport)
      # EMAIL_SMTP_HOST: "localhost"
      EMAIL_TRANSPORT: "smtp"
      EMAIL_SMTP_HOST: "smtp.gmail.com"
      # Use SMTP pooling
      EMAIL_SMTP_POOL: true
      EMAIL_SMTP_PORT: 587
      EMAIL_SMTP_SECURE: false # Use TLS
      EMAIL_SMTP_IGNORE_TLS: false
      EMAIL_SMTP_USER: "trinhthuc130902@gmail.com"
      # EMAIL_SMTP_PASSWORD: "vttl bevl zbav lvjd"
      EMAIL_SMTP_PASSWORD: "gkkt dvcr sbry mcya"

      USER_REGISTER_URL_ALLOW_LIST:  "http://162.248.102.236:8055"


networks:
  directus:
